---
- name: Collect eigen git tags
  shell: git ls-remote --tags --exit-code --refs https://gitlab.com/libeigen/eigen.git | sed -E 's/^[[:xdigit:]]+[[:space:]]+refs\/tags\/(.+)/\1/g'
  register: eigen_git_tags

- name: Check whether specified Eigen version in Eigen tag list
  assert:
    that:
      - eigen_ver in eigen_git_tags.stdout_lines
    fail_msg: "{{ eigen_ver }} doesn't exist in taglist"
    success_msg: "{{ eigen_ver }} exists in taglist"

- name: Check whether CUDA Toolkit version exists in cuda_tk_dict
  assert:
    that:
      - cuda_tk_ver in cuda_tk_dict.keys()
    fail_msg: "{{ cuda_tk_ver }} doesn't exist in cuda_tk_dict"
    success_msg: "{{ cuda_tk_ver }} exists in cuda_tk_dict"

- name: Check whether ROS version exists in ros_distro_dict
  assert:
    that:
      - os_release in ros_distro_dict.keys()
    fail_msg: "{{ os_release }} doesn't exist in ros_distro_dict"
    success_msg: "{{ os_release }} exists in ros_distro_dict"

- name: Check whether PeakCAN version exists in pcan_ver_list
  assert:
    that:
      - pcan_ver in pcan_ver_list
    fail_msg: "{{ pcan_ver }} doesn't exist in "
    success_msg: "{{ pcan_ver }} exists in pcan_ver_list"

- name: Collect trtorch git tags
  shell: git ls-remote --tags --exit-code --refs https://github.com/NVIDIA/TRTorch.git | sed -E 's/^[[:xdigit:]]+[[:space:]]+refs\/tags\/(.+)/\1/g'
  register: trtorch_git_tags

- name: Check whether specified TRTorch version in TRTorch tag list
  assert:
    that:
      - trtorch_ver in trtorch_git_tags.stdout_lines
    fail_msg: "{{ trtorch_ver }} doesn't exist in taglist"
    success_msg: "{{ trtorch_ver }} exists in taglist"
