---
- name: Executing playbook.yml
  hosts: localhost
  vars_files:
    - vars/settings.yml
    - vars/defaults.yml
    - secrets/secrets.yml
  handlers:
    - include: handlers/apt_handlers.yml
  pre_tasks:
    - name: Trigger apt_update
      shell: echo ""
      notify: apt_update
  roles:
    - common
    - terminal_velocity # tools to make you faster
    - git
    - pip
    - sshd
    - cmake
    - eigen
    - g2o
    - cuda
    - cudnn
    - tensorrt
    # - ros
    - julia
    - pytorch
    - docker
    # Sensor Drivers
    - flycap # For APM
    - baumer # For AQC
    - peakcan
    - robosense
    - linuxcan
    - kvaser
    # Misc
    - ms_teams
    - zoom
    - vscode
