- name: Configure typora
  shell: |
    wget -qO - https://typora.io/linux/public-key.asc | sudo apt-key add -
    sudo add-apt-repository 'deb https://typora.io/linux ./'
    sudo apt update

- name: Install typora
  apt:
    name: typora
    state: present
