- name: Add apt repo for lazygit
  become: true
  apt_repository:
    repo: "{{ ppa_lazygit }}"
    state: present
    update_cache: true
  notify:
    - post_add_apt_handler
    - apt_update

- meta: flush_handlers

- name: Install lazygit
  become: true
  apt:
    name: "{{ item }}"
    state: present
  loop:
    - lazygit
