- name: Install cmake related apt packages
  become: true
  become_method: sudo
  apt:
    name: "{{ item }}"
    state: present
  loop:
    - wget
    - apt-transport-https
    - ca-certificates
    - gnupg
    - software-properties-common
    # - kitware-archive-keyring

- name: Obtain Kitware signing key using wget
  shell: "wget -O - {{ kitware_gpg_key }} 2>/dev/null | gpg --dearmor - | sudo tee /etc/apt/trusted.gpg.d/kitware.gpg >/dev/null"
  args:
    warn: false

- name: Add apt repo for cmake
  apt_repository:
    repo: "{{ cmake_repo }}"
    state: present
    update_cache: true
  notify:
    - post_add_apt_handler
    - apt_update
    - apt_upgrade

- name: Ensure CMake is upgraded
  apt:
    name: cmake
    state: latest
  register: upgrade_cmake_status
  until: upgrade_cmake_status is success
  delay: 1
  retries: 5
