- name: Install cmake related apt packages
  become: true
  become_method: sudo
  apt:
    name: "{{ item }}"
    state: present
  loop:
    - wget
    - apt-transport-https
    - ca-certificates
    - gnupg
    - software-properties-common

- name: Obtain Kitware signing key using wget
  shell: wget -O - https://apt.kitware.com/keys/kitware-archive-latest.asc 2>/dev/null | gpg --dearmor - | sudo tee /etc/apt/trusted.gpg.d/kitware.gpg >/dev/null
  warn: false

- name: Add apt repo for cmake
  apt_repository:
    repo: "{{ cmake_repo }}"
    state: present
    update_cache: true
  notify:
    - remove_apt_lock
    - remove_dpkg_lock
    - disable_unattended_updates
    - disable_unattended_upgrades
    - remove_unattended_upgrades
    - apt_update_upgrade

- name: Ensure CMake is upgraded
  apt:
    name: cmake
    state: latest
  register: upgrade_cmake_status
  until: upgrade_cmake_status is success
  delay: 1
  retries: 5
