---
- name: Get Microsoft GPG key
  shell: |
    wget -qO- https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor > packages.microsoft.gpg && \
    sudo install -o root -g root -m 644 packages.microsoft.gpg /etc/apt/trusted.gpg.d/

- name: Remove downloaded GPG key
  file:
    path: packages.microsoft.gpg
    state: absent

- name: Add VSCode apt repo
  shell: |
    sudo sh -c 'echo "deb [arch=amd64 signed-by=/etc/apt/trusted.gpg.d/packages.microsoft.gpg] https://packages.microsoft.com/repos/code stable main" > /etc/apt/sources.list.d/vscode.list'
  notify:
    - apt_update

- meta: flush_handlers

- name: Install apt-transport-https
  become: true
  apt:
    name: apt-transport-https
    state: present

- name: Install vscode
  become: true
  apt:
    name: code
    state: present

- name: Install vscode extensions
  shell: "code --install-extension {{ item }}"
  loop:
    # General
    - Shan.code-settings-sync
  when: vscode_extensions_install == true

- name: Run JetBrains Mono install script
  shell: |
    /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/JetBrains/JetBrainsMono/master/install_manual.sh)"

# - name: Download JetBrains Mono font
#   shell: "wget https://download.jetbrains.com/fonts/JetBrainsMono-2.225.zip -P {{ install_dir }} --quiet"

# - name: Unzip font file
#   unarchive:
#     src: "{{ install_dir }}/JetBrainsMono-2.225.zip"
#     dest: "{{ install_dir }}"

# - name: Install font-manager
#   become: true
#   apt:
#     name: font-manager
#     state: present

# - name: Install
#   shell: "cd {{ install_dir }}/fonts/ttf/ && font-manager -i *"
