---
- name: Configure LXDE enironment
  become: true
  become_method: sudo
  shell: |
    sudo apt install lxde
    sudo dpkg-reconfigure lightdm
    sudo dpkg --configure -a
    sudo apt remove --purge gdm3

# - name: Add keyboard shortcuts for LXDE
#   blockinfile:
#     block: |
#       <!-- Launch LXTerminal with Ctrl+Alt+t-->
#           <keybind key="C-A-t">
#             <action name="Execute">
#               <command>lxterminal</command>
#             </action>
#           </keybind>

- name: Install some apt packages
  become: true
  become_method: sudo
  apt:
    name: "{{ item }}"
    state: present
  loop:
    - nano
    - git
    - exfat-fuse
    - exfat-utils
