- name: "Install common packages"
  apt:
    name: "{{ item }}"
    state: present
  loop:
    - git
    - terminator
    - vim
    - net-tools
    - gcc
    - curl
    - htop
# - name: "Adding lines to .bashrc"
#   lineinfile: name=~/.bashrc line="asdfgh"