- name: Install some common apt packages
  become_user: yes
  apt:
    name: "{{ item }}"
    state: present
  loop:
    - git
    - terminator
    - vim
    - net-tools
    - gcc
    - curl
    - htop

- name: Ensure bash history has time stamps
  lineinfile:
    path: "{{ home_dir }}/.bashrc"
    line: HISTTIMEFORMAT="%d/%m/%y %T "
    state: present
    backup: no
    insertafter: EOF

- name: Store lsb_release -sc in variable
  shell: lsb_release -sc
  register: ubuntu_ver

- name: Test ros_distribution dict
  debug: msg="ROS Distribution should be {{ ros_distribution[ubuntu_ver.stdout] }}"