- name: Install some common apt packages
  become: true
  become_method: sudo
  apt:
    name: "{{ item }}"
    state: present
  loop:
    - git
    - terminator
    - vim
    - net-tools
    - gcc
    - wget
    - curl
    - tlp
    - htop
    - python
    - python-pip
    - python3
    - python3-pip

- name: Add apt repo for git
  apt_repository:
    repo: "{{ ppa_git }}"
    state: present
    update_cache: true
  notify:
    - remove_apt_lock
    - remove_dpkg_lock
    - disable_unattended_updates
    - disable_unattended_upgrades
    - remove_unattended_upgrades
    - apt_update_upgrade

# - name: Run dpkg --configure -a
#   become: true
#   become_method: sudo
#   command: dpkg --configure -a

- name: Ensure Git is upgraded
  apt:
    name: git
    state: latest
  register: upgrade_git_status
  until: upgrade_git_status is success
  delay: 1
  retries: 5

- name: Upgrade python3 pip
  pip:
    name: pip
    executable: pip3
    extra_args: --upgrade

- name: Upgrade python2 pip
  pip:
    name: pip
    executable: pip2
    extra_args: --upgrade

- name: Adding nano settings
  blockinfile:
    path: "{{ home_dir }}/.nanorc"
    marker: "# {mark} USER SETTINGS - ANSIBLE MANAGED BLOCK"
    block: |
      set tabsize 4
      set tabstospaces
      set softwrap
    create: yes

- name: Adding time stamps to bash history
  blockinfile:
    path: "{{ home_dir }}/.bashrc"
    marker: "# {mark} USER BASH SETTINGS - ANSIBLE MANAGED BLOCK"
    block: |
      HISTTIMEFORMAT="%d/%m/%y %T "

- name: Enabling ttyUSB0 permissions
  become: true
  become_method: sudo
  blockinfile:
    path: "/etc/udev/rules.d/60-extra-acl.rules"
    marker: "# {mark} USER PERMISSION SETTINGS - ANSIBLE MANAGED BLOCK"
    block: |
      KERNEL=="ttyUSB0", TAG+="udev-acl", TAG+="uaccess"
    create: yes

- name: "Creating installation directory at {{ install_dir }}"
  file:
    path: "{{ install_dir }}"
    state: directory
# - name: Test ros_distribution dict
#   debug: msg="ROS Distribution should be {{ ros_distribution[os_release] }}"

# - name: Distribution
#   debug: msg="{{ os_distro }}, {{ os_release }}"

# - name: Test dict
#   debug: msg="{{ cuda_tk_driver["11.0"]["apt"] }}"
