---
- name: Install some common apt packages
  become: true
  become_method: sudo
  apt:
    name: "{{ item }}"
    state: latest
  loop:
    - git
    - terminator
    - vim
    - net-tools
    - gcc
    - wget
    - curl
    - tlp
    - htop
    - python
    - python-dev
    - python3
    - python3-dev
    - build-essential
    - "linux-headers-{{ os_kernel }}"
    - xz-utils
    - python-setuptools
    - libboost-python-dev
    - libboost-thread-dev
    - tree

- name: Uninstall update-notifier apt packages, and unattended-upgrades
  become: true
  become_method: sudo
  apt:
    name: "{{ item }}"
    state: absent
  loop:
    - update-notifier
    - update-notifier-common
    - unattended-upgrades

- name: Adding nano settings
  become: true
  become_method: sudo
  blockinfile:
    path: "/etc/nanorc"
    marker: "# {mark} USER SETTINGS - ANSIBLE MANAGED BLOCK"
    block: |
      set tabsize 4
      set tabstospaces
      set softwrap

- name: Adding time stamps to bash history
  blockinfile:
    path: "{{ home_dir }}/.bashrc"
    marker: "# {mark} USER BASH SETTINGS - ANSIBLE MANAGED BLOCK"
    block: |
      HISTTIMEFORMAT="%D %l:%M"

- name: Enabling ttyUSB* and ttyS* permissions
  become: true
  become_method: sudo
  blockinfile:
    path: "/etc/udev/rules.d/60-extra-acl.rules"
    marker: "# {mark} USER PERMISSION SETTINGS - ANSIBLE MANAGED BLOCK"
    block: |
      KERNEL=="ttyUSB[0-9]*", TAG+="udev-acl", TAG+="uaccess"
      KERNEL=="ttyS[0-30]*", TAG+="udev-acl", TAG+="uaccess"
    create: yes

- name: "Creating installation directory at {{ install_dir }}"
  file:
    path: "{{ install_dir }}"
    state: directory
