---
- name: Install pip3
  become: true
  apt:
    name: "{{ item }}"
    state: latest
  loop:
    - python3-pip
    # - python-pip

# - name: Upgrade python2 pip
#   pip:
#     name: pip
#     executable: pip2
#     extra_args: --upgrade

- name: Upgrade python3 pip
  pip:
    name: pip
    executable: pip3
    extra_args: --upgrade

# this works well when you have both pip2 and pip3 installed
- name: Set default pip to pip3
  shell: python3 -m pip install --upgrade --force pip

