---
- name: remove_apt_lock
  become: true
  become_method: sudo
  file:
    path: "{{ item }}"
    state: absent
  loop:
    - /var/lib/apt/lists/lock
    - /var/cache/apt/archives/lock

- name: remove_dpkg_lock
  become: true
  become_method: sudo
  file:
    path: "{{ item }}"
    state: absent
  loop:
    - /var/lib/dpkg/lock
    - /var/lib/dpkg/lock-frontend

- name: disable_unattended_updates
  become: true
  become_method: sudo
  lineinfile:
    path: "{{ item }}"
    regexp: ^APT::Periodic::Update-Package-Lists
    line: APT::Periodic::Update-Package-Lists "0";;
  loop:
    - /etc/apt/apt.conf.d/10periodic
    - /etc/apt/apt.conf.d/20auto-upgrades

- name: disable_unattended_upgrades
  become: true
  become_method: sudo
  lineinfile:
    path: /etc/apt/apt.conf.d/20auto-upgrades
    regexp: ^APT::Periodic::Unattended-Upgrade
    line: APT::Periodic::Unattended-Upgrade "0";

- name: remove_unattended_upgrades
  become: true
  become_method: sudo
  apt:
    name: unattended-upgrades
    state: absent

- name: apt_update_upgrade
  become: true
  become_method: sudo
  apt:
    upgrade: yes
    update_cache: yes
