---
# Remove apt lock, triggers handler chain of 4 other tasks
# START HANDLER CHAIN
- name: post_add_apt_handler
  become: true
  become_method: sudo
  file:
    path: "{{ item }}"
    state: absent
  loop:
    - /var/lib/apt/lists/lock
    - /var/cache/apt/archives/lock
  notify:
    - remove_dpkg_lock

- name: remove_dpkg_lock
  become: true
  become_method: sudo
  file:
    path: "{{ item }}"
    state: absent
  loop:
    - /var/lib/dpkg/lock
    - /var/lib/dpkg/lock-frontend
  notify:
    - disable_unattended_updates

- name: disable_unattended_updates
  become: true
  become_method: sudo
  lineinfile:
    path: "{{ item }}"
    regexp: ^APT::Periodic::Update-Package-Lists
    line: APT::Periodic::Update-Package-Lists "0";;
  loop:
    - /etc/apt/apt.conf.d/10periodic
    - /etc/apt/apt.conf.d/20auto-upgrades
  notify:
    - disable_unattended_upgrades

- name: disable_unattended_upgrades
  become: true
  become_method: sudo
  lineinfile:
    path: /etc/apt/apt.conf.d/20auto-upgrades
    regexp: ^APT::Periodic::Unattended-Upgrade
    line: APT::Periodic::Unattended-Upgrade "0";
  notify:
    - remove_unattended_upgrades

- name: remove_unattended_upgrades
  become: true
  become_method: sudo
  apt:
    name: unattended-upgrades
    state: absent
# END HANDLER CHAIN

- name: apt_update
  become: true
  become_method: sudo
  apt:
    upgrade: no
    update_cache: true

- name: apt_upgrade
  become: true
  become_method: sudo
  apt:
    upgrade: true
