- name: Enabling ttyUSB* and ttyS* permissions
  become: true
  blockinfile:
    path: /etc/udev/rules.d/60-extra-acl.rules
    marker: "# {mark} USER PERMISSION SETTINGS - ANSIBLE MANAGED BLOCK"
    block: |
      KERNEL=="ttyUSB[0-9]*", TAG+="udev-acl", TAG+="uaccess"
      KERNEL=="ttyS[0-30]*", TAG+="udev-acl", TAG+="uaccess"
    create: yes
