---
cuda_tk_ver: "11.0.2"
eigen_ver: "3.3.9"
tensorrt_ver: "7.2.1.6"
pcan_ver: "8.10.2"
pcan_api_ver: "4.3.1.3" # unused atm
pycuda_ver: "2020.1"
trtorch_ver: "v0.1.0"
cxx11_ABI: true
julia_ver: "1.5.2"
