---
cuda_tk_ver: "11.0.2"
cudnn_ver: "8.0.5.39"
eigen_ver: "3.3.9"
tensorrt_ver: "7.2.1.6"
pcan_ver: "8.10.2"
# pcan_api_ver: "4.3.1.3" # unused atm
pycuda_ver: "2020.1"
julia_ver: "1.5.2"
torch_ver: "1.7.1+cu110"
