---
- name: "Check if {{ baumer_deb_file }} exists in {{ install_dir }}"
  stat:
    path: "{{ install_dir }}/{{ baumer_deb_file }}"
  register: baumer_deb

- name: "Download {{ baumer_deb_file }}"
  shell: "wget {{ baumer_deb_url  }} -P {{ install_dir }} --quiet"
  when: baumer_deb.stat.exists == false

- name: Install Baumer
  become: true
  apt:
    deb: "{{ install_dir }}/{{ baumer_deb_file }}"
