---
home_dir: "{{ ansible_env.HOME }}"
install_dir: "{{ home_dir }}/install_dir"
os_distro: "{{ ansible_distribution | lower }}"
os_distro_ver: "{{ ansible_distribution_version | replace('.','') }}"
# Includes . delimiter
os_release: "{{ ansible_distribution_release }}"
os_kernel: "{{ ansible_kernel }}"
arch: "{{ ansible_architecture }}"

eigen_file: "eigen-{{ eigen_ver }}.tar.bz2"

# RoS Distribution lookup
ros_distribution:
  "trusty": "indigo"
  "xenial": "kinetic"
  "bionic": "melodic"
  "focal": "noetic"

# NVIDIA driver versioncorresponding to CUDA version
cuda_tk_dict:
  "11.0.2":
    apt_ver: "11-0"
    nvidia_driver: "450.51.05"

cuda_deb_file: "cuda-repo-{{ os_distro }}{{ os_distro_ver }}-{{ cuda_tk_dict[cuda_tk_ver][\"apt_ver\"] }}-local_{{ cuda_tk_ver }}-{{ cuda_tk_dict[cuda_tk_ver][\"nvidia_driver\"] }}-1_amd64.deb"
cuda_apt_key: "/var/cuda-repo-{{ os_distro }}{{ os_distro_ver }}-{{ cuda_tk_dict[cuda_tk_ver][\"apt_ver\"] }}-local/7fa2af80.pub"

nvidia_url: "https://developer.download.nvidia.com/compute/cuda"

# APT Repositories
cmake_repo: "deb https://apt.kitware.com/ubuntu/ {{ os_release }} main"
cmake_rc_repo: "deb https://apt.kitware.com/ubuntu/ {{ os_release }}-rc main"
ppa_git: "ppa:git-core/ppa"
