---
- name: Uninstall openssh-client
  become: true
  become_method: sudo
  apt:
    name: "{{ item }}"
    state: absent
  loop:
    - openssh-client

- name: Install openssh-server
  become: true
  become_method: sudo
  apt:
    name: "{{ item }}"
    state: present
  loop:
    - openssh-server

- name: Check status of sshd service
  service_facts:
  register: service_state
- debug:
    var: service_state.ansible_facts.services["sshd.service"].state

- name: Start sshd service if not started
  become: yes
  service:
    name: sshd
    state: started
  when: service_state.ansible_facts.services["sshd.service"].state == false
