---
- name: Configure git aliases
  blockinfile:
    path: "{{ home_dir }}/.gitconfig"
    marker: "# {mark} GIT SETTINGS - ANSIBLE MANAGED BLOCK"
    block: |
      [alias]
          co = checkout
          br = branch
          ci = commit
          st = status
          rt = reset
          rb = rebase
          lg = lg1 # default git lg behaviour
          lg1 = lg1-specific --all
          lg2 = lg2-specific --all
          lg3 = lg3-specific --all

          lg1-specific = log --graph --abbrev-commit --decorate --format=format:'%C(bold blue)%h%C(reset) - %C(bold green)(%ar)%C(reset) %C(white)%s%C(reset) %C(dim white)- %an%C(reset)%C(auto)%d%C(reset)'
          lg2-specific = log --graph --abbrev-commit --decorate --format=format:'%C(bold blue)%h%C(reset) - %C(bold cyan)%aD%C(reset) %C(bold green)(%ar)%C(reset)%C(auto)%d%C(reset)%n''          %C(white)%s%C(reset) %C(dim white)- %an%C(reset)'
          lg3-specific = log --graph --abbrev-commit --decorate --format=format:'%C(bold blue)%h%C(reset) - %C(bold cyan)%aD%C(reset) %C(bold green)(%ar)%C(reset) %C(bold cyan)(committed: %cD)%C(reset) %C(auto)%d%C(reset)%n''          %C(white)%s%C(reset)%n''          %C(dim white)- %an <%ae> %C(reset) %C(dim white)(committer: %cn <%ce>)%C(reset)'
    create: yes

- name: Add apt repo for git
  become: true
  apt_repository:
    repo: "{{ ppa_git }}"
    state: present
    update_cache: true
  notify:
    - post_add_apt_handler
    - apt_update
    - apt_upgrade

- meta: flush_handlers

- name: Ensure Git is upgraded
  apt:
    name: git
    state: latest
  register: upgrade_git_status
  until: upgrade_git_status is success
  delay: 1
  retries: 3
