---
- name: Collect Julia git tags
  shell: git ls-remote --tags --exit-code --refs https://github.com/JuliaLang/julia.git | sed -E 's/^[[:xdigit:]]+[[:space:]]+refs\/tags\/(.+)/\1/g'
  register: julia_git_tags

- name: Check whether specified Julia version in Julia tag list
  assert:
    that:
      - julia_git_tag in julia_git_tags.stdout_lines
    fail_msg: "{{ julia_git_tag }} doesn't exist in taglist"
    success_msg: "{{ julia_git_tag }} exists in taglist"

- name: "Check if {{ julia_file }} exists"
  stat:
    path: "{{ install_dir }}/{{ julia_file }}"
  register: julia_tar

- name: "Download julia tar.gz to {{ install_dir }}"
  shell: "wget https://julialang-s3.julialang.org/bin/linux/x64/{{ julia_ver[:3] }}/{{ julia_file }} -P {{ install_dir }} --quiet"
  when: julia_tar.stat.exists == false

- name: Unarchive julia tar.gz to /opt/
  become: true
  unarchive:
    src: "{{ install_dir }}/{{ julia_file }}"
    dest: /opt/

- name: Create julia symlink
  become: true
  file:
    src: "/opt/julia-{{ julia_ver }}/bin/julia"
    dest: "/usr/local/bin/julia"
    state: link

- name: "Copy {{ julia_init_setup_file }} to {{ install_dir }}"
  copy:
    src: "files/{{ julia_init_setup_file }}"
    dest: "{{ install_dir }}"

- name: "Execute {{ julia_init_setup_file }}"
  shell: "julia {{ install_dir }}/{{ julia_init_setup_file }}"
