- name: Ensure CUDA folders are added to $PATH
  blockinfile:
    path: "{{ home_dir }}/.bashrc"
    marker: "# {mark} CUDA TOOLKIT SETTINGS - ANSIBLE MANAGED BLOCK"
    block: |
      export PATH="/usr/local/cuda/bin:$PATH"
      export LD_LIBRARY_PATH="/usr/local/cuda/lib64:$LD_LIBRARY_PATH"
      export LD_LIBRARY_PATH="/usr/local/cuda/extras/CUPTI/lib64:$LD_LIBRARY_PATH"
