- name: Download cuda preferences file
  shell: "wget {{ nvidia_url }}/repos/{{ os_distro }}{{ os_distro_ver }}/{{ arch }}/{{ cuda_apt_pref_pin }} -P {{ install_dir }} --quiet"

- name: Add cuda preferences to apt
  become: true
  become_method: sudo
  shell: "mv {{ install_dir }}/{{ cuda_apt_pref_pin }} /etc/apt/preferences.d/cuda-repository-pin-600"

- name: Check if local deb installer exists
  stat:
    path: "{{ install_dir }}/{{ cuda_deb_file }}"
  register: cuda_local_deb

- name: Download cuda local deb installer (big boi)
  shell: "wget {{ nvidia_url }}/{{ cuda_tk_ver }}/local_installers/{{ cuda_deb_file }} -P {{ install_dir }} --quiet"
  when: cuda_local_deb.stat.exists == false

- name: Install cuda via .deb file
  become: true
  become_method: sudo
  apt:
    deb: "{{ install_dir }}/{{ cuda_deb_file }}"

- name: Add apt key for cuda
  become: true
  become_method: sudo
  apt_key:
    file: "{{ cuda_apt_key }}"
    state: present
  notify:
    - apt_update

- meta: flush_handlers

- name: "Install {{ cuda_apt_pkg }} and {{ cuda_tk_apt_pkg }}"
  become: true
  become_method: sudo
  apt:
    name: "{{ item }}"
    state: present
  loop:
    - "{{ cuda_apt_pkg }}"
    - "{{ cuda_tk_apt_pkg }}"

- name: Add CUDA settings are added to ~/.bashrc
  blockinfile:
    path: "{{ home_dir }}/.bashrc"
    marker: "# {mark} CUDA TOOLKIT SETTINGS - ANSIBLE MANAGED BLOCK"
    block: |
      export PATH="/usr/local/cuda/bin:$PATH"
      export LD_LIBRARY_PATH="/usr/local/cuda/lib64:$LD_LIBRARY_PATH"
      export LD_LIBRARY_PATH="/usr/local/cuda/extras/CUPTI/lib64:$LD_LIBRARY_PATH"

- name: Adding settings to /etc/modprobe.d/blacklist.conf
  become: true
  become_method: sudo
  blockinfile:
    path: /etc/modprobe.d/blacklist.conf
    marker: "# {mark} CUDA TOOLKIT SETTINGS - ANSIBLE MANAGED BLOCK"
    block: |
      blacklist nouveau
      options nouveau modeset=0

- name: sudo update-initramfs -u
  become: true
  become_method: sudo
  shell: update-initramfs -u