---
- name: Install PyTorch
  shell: pip3 install torch==1.7.1+cu110 torchvision==0.8.2+cu110 torchaudio===0.7.2 -f https://download.pytorch.org/whl/torch_stable.html

- name: Check if Libtorch (pre-cxx11 ABI) exists
  stat:
    path: "{{ install_dir }}/libtorch-shared-with-deps-1.7.1+cu110.zip"
  register: libtorch_pre_cxx11_abi

- name: Download Libtorch (pre-cxx11 ABI)
  shell: "wget https://download.pytorch.org/libtorch/cu110/libtorch-shared-with-deps-1.7.1%2Bcu110.zip -P {{ install_dir }} --quiet"
  when: (cxx11_ABI == false and libtorch_pre_cxx11_abi.stat.exists == false )

- name: Check if Libtorch (cxx11 ABI) exists
  stat:
    path: "{{ install_dir }}/libtorch-cxx11-abi-shared-with-deps-1.7.1+cu110.zip"
  register: libtorch_cxx11_abi

- name: Download Libtorch (cxx11 ABI)
  shell: "wget https://download.pytorch.org/libtorch/cu110/libtorch-cxx11-abi-shared-with-deps-1.7.1%2Bcu110.zip -P {{ install_dir }} --quiet"
  when: (cxx11_ABI == true and libtorch_cxx11_abi.stat.exists == false )

- name: Unarchive libtorch/ to /opt/
  unarchive:
    src: "{{ install_dir }}/{{ eigen_file }}"
    dest: "{{ install_dir }}"
