- name: Install eigen related apt packages
  become: true
  become_method: sudo
  apt:
    name: "{{ item }}"
    state: present
  loop:
    - libblas-dev
    - build-essential
    - libeigen3-dev

- name: "Download eigen {{ eigen_ver }} from gitlab"
  get_url:
    url: "https://gitlab.com/libeigen/eigen/-/archive/{{ eigen_ver }}/{{ eigen_file }}"
    dest: "{{ install_dir }}"

- name: "Unarchive {{ eigen_file }}"
  unarchive:
    src: "{{ install_dir }}/{{ eigen_file }}"
    dest: "{{ install_dir }}"

- name: "Create {{ install_dir }}/eigen-{{ eigen_ver }}/build/"
  file:
    path: "{{ install_dir }}/eigen-{{ eigen_ver }}/build"
    state: directory

- name: Run cmake without changing directories
  shell: "cmake -S {{ install_dir }}/eigen-{{ eigen_ver }} -B {{ install_dir }}/eigen-{{ eigen_ver }}/build/"

- name: "make -j{{ ansible_processor_vcpus }}"
  make:
    chdir: "{{ install_dir }}/eigen-{{ eigen_ver }}/build/"
    params:
      NUM_THREADS: "{{ ansible_processor_vcpus }}"

- name: sudo make install
  become: true
  become_method: sudo
  shell: make install --debug=basic
  args:
    chdir: "{{ install_dir }}/eigen-{{ eigen_ver }}/build/"
