# ANSIBLE MANAGED FILE
alias sysupd="sudo apt update && sudo apt upgrade -y"
alias q="exit"
alias c="clear"
alias lt="ls --human-readable --size -1 -S --classify"
alias py3="python3"
alias py2="python2"
alias pip3="python3 -m pip"
alias pip2="python2 -m pip"
alias jlab="jupyter-lab"
alias jnb="jupyter notebook"
alias ga="git add"
alias gc="git commit"
alias gst="git status"
alias gcl="git clone"
alias gpl="git pull"
alias gps="git push"
# for working with virtual environments
alias ae="activate"
alias de="deactivate"
alias cae="conda activate"
alias cde="conda deactivate"
# ANSIBLE MANAGED FILE
