---
- name: Install some common apt packages
  become: true
  become_method: sudo
  apt:
    name: "{{ item }}"
    state: latest
  loop:
    - git
    - terminator
    - snapd
    - byobu
    - blueman
    - vim
    - net-tools
    - gcc
    - wget
    - curl
    - tlp
    - htop
    - tree
    - software-properties-common
    - build-essential
    - "linux-headers-{{ os_kernel }}"
    - xz-utils
    - python
    - python-dev
    - python3
    - python3-dev
    - python-setuptools
    - libboost-python-dev
    - libboost-thread-dev

- name: Uninstall update-notifier apt packages, and unattended-upgrades
  become: true
  become_method: sudo
  apt:
    name: "{{ item }}"
    state: absent
  loop:
    - update-notifier
    - update-notifier-common
    - unattended-upgrades

- name: Adding nano settings
  become: true
  become_method: sudo
  blockinfile:
    path: /etc/nanorc
    marker: "# {mark} USER SETTINGS - ANSIBLE MANAGED BLOCK"
    block: |
      set tabsize 4
      set tabstospaces
      set softwrap

- name: Adding time stamps to bash history
  blockinfile:
    path: "{{ home_dir }}/.bashrc"
    marker: "# {mark} USER BASH SETTINGS - ANSIBLE MANAGED BLOCK"
    block: |
      HISTTIMEFORMAT="%D %l:%M "
      export PATH=$PATH:~/bin

- name: Enabling ttyUSB* and ttyS* permissions
  become: true
  become_method: sudo
  blockinfile:
    path: /etc/udev/rules.d/60-extra-acl.rules
    marker: "# {mark} USER PERMISSION SETTINGS - ANSIBLE MANAGED BLOCK"
    block: |
      KERNEL=="ttyUSB[0-9]*", TAG+="udev-acl", TAG+="uaccess"
      KERNEL=="ttyS[0-30]*", TAG+="udev-acl", TAG+="uaccess"
    create: yes

- name: Copy ansible/files/.bash_aliases to ~/.bash_aliases
  copy:
    src: files/.bash_aliases
    dest: ~/.bash_aliases

- name: "Creating installation directory at {{ install_dir }}"
  file:
    path: "{{ install_dir }}"
    state: directory

- name: Create bin directory at ~/bin
  file:
    path: ~/bin
    state: directory
