---
- name: Install some common apt packages
  become: true
  apt:
    name: "{{ item }}"
    state: latest
  loop:
    - git
    - snapd
    - byobu
    - blueman
    - vim
    - neovim
    - net-tools
    - gcc
    - wget
    - curl
    - tlp
    - htop
    - tree
    - software-properties-common
    - build-essential
    - "linux-headers-{{ os_kernel }}"
    - xz-utils
    - python
    - python-dev
    - python3
    - python3-dev
    - python-setuptools
    - libboost-python-dev
    - libboost-thread-dev

- name: Uninstall update-notifier apt packages, and unattended-upgrades
  become: true
  apt:
    name: "{{ item }}"
    state: absent
  loop:
    - update-notifier
    - update-notifier-common
    - unattended-upgrades

- name: Adding time stamps to bash history
  blockinfile:
    path: "{{ home_dir }}/.bashrc"
    marker: "# {mark} USER BASH SETTINGS - ANSIBLE MANAGED BLOCK"
    block: |
      HISTTIMEFORMAT="%D %l:%M "
      export PATH=$PATH:~/bin

- name: Copy ansible/files/.bash_aliases to ~/.bash_aliases
  copy:
    src: files/.bash_aliases
    dest: ~/.bash_aliases

- name: "Creating installation directory at {{ install_dir }}"
  file:
    path: "{{ install_dir }}"
    state: directory

- name: Create bin directory at ~/bin
  file:
    path: ~/bin
    state: directory
