---
- name: Executing playbook.yml
  hosts: localhost
  # become: true
  vars_files:
    - vars/defaults.yml
    - vars/ros.yml
    - vars/cuda.yml
    - vars/ppa.yml
  roles:
    - common
    - cuda
