---
- name: Executing playbook.yml
  hosts: localhost
  vars_files:
    - vars/settings.yml
    - vars/defaults.yml
    - secrets/secrets.yml
  # Run these to simply trigger the apt_update & apt_upgrade handlers in roles/common/handlers/main.yml before installing packages
  pre_tasks:
    - name: Run sudo apt update
      shell: echo "" # dummy task
      notify: apt_update
    - name: Run sudo apt upgrade
      shell: echo "" # dummy task
      notify: apt_upgrade
  roles:
    - check_vars
    - common
    - cmake
    - eigen
    - cuda
    - cudnn
    - tensorrt
    - ros
    - julia
    # - flycap # For APM
    # - baumer # For AQC
    # - netplan
    - peakcan
    - robosense
    - linuxcan
    - kvaser

# - name: Import & run sensors.yml
#   import_playbook: sensors.yml