---
- name: Executing playbook.yml
  hosts: localhost
  # become: true
  vars_files:
    - vars/settings.yml
    - vars/defaults.yml
  roles:
    - check_vars
    - common
    - cuda
    - cmake
    - eigen
    - ros