---
- name: Executing playbook.yml
  hosts: localhost
  vars_files:
    - vars/settings.yml
    - vars/defaults.yml
    - secrets/secrets.yml
  handlers:
    - include: handlers/apt_handlers.yml
  pre_tasks:
    - name: Trigger apt_update
      shell: echo ""
      notify: apt_update
  roles:
    - check_vars
    - common
    - git
    - cmake
    - eigen
    - g2o
    - cuda
    - cudnn
    - tensorrt
    - ros
    - julia
    - flycap # For APM
    - baumer # For AQC
    # - netplan
    # - torch
    # - trtorch
    - peakcan
    - robosense
    - linuxcan
    - kvaser
