---
- name: Remove old version of docker
  become: true
  apt:
    name: "{{ item  }}"
    state: absent
  loop:
    - docker
    - docker-engine
    - docker.io
    - containerd
    - runc

- name: Install dependencies
  become: true
  apt:
    name: "{{ item  }}"
    state: present
  loop:
    - apt-transport-https
    - ca-certificates
    - curl
    - gnupg-agent
    - software-properties-common

- name: Add docker GPG key
  shell: |
    curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add - && \
    sudo apt-key fingerprint 0EBFCD88

- name: Add docker apt repo
  shell: |
    sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ os_release }} stable"
  notify: apt_update

- meta: flush_handlers

- name: Install docker
  become: true
  apt:
    name: "{{ item  }}"
    state: present
  loop:
    - docker-ce
    - docker-ce-cli
    - containerd.io

# Install NVIDIA Container Toolkit
- name: Add nvidia-docker apt repo
  shell: |
    distribution=$(. /etc/os-release;echo $ID$VERSION_ID) \
      && curl -s -L https://nvidia.github.io/nvidia-docker/gpgkey | sudo apt-key add - \
      && curl -s -L https://nvidia.github.io/nvidia-docker/$distribution/nvidia-docker.list | sudo tee /etc/apt/sources.list.d/nvidia-docker.list
  notify: apt_update

- meta: flush_handlers

- name: Install NVIDIA Container Toolkit
  become: true
  apt:
    name: "{{ item  }}"
    state: present
  loop:
    - nvidia-docker2

# # USE AT YOUR OWN RISK
# - name: "Add user to docker group, to remove need for sudo"
#   shell: sudo usermod -aG docker $USER

- name: Install docker compose
  pip:
    name: docker-compose
    executable: pip3
