---
- name: Remove old version of docker
  become: true
  apt:
    name: "{{ item  }}"
    state: absent
  loop:
    - docker
    - docker-engine
    - docker.io
    - containerd
    - runc

- name: Install dependencies
  become: true
  apt:
    name: "{{ item  }}"
    state: present
  loop:
    - apt-transport-https
    - ca-certificates
    - curl
    - gnupg
    - gnupg-agent
    - software-properties-common
    - lsb-release

- name: Add docker GPG key
  shell: |
    curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg

- name: Add docker stable repository
  become: true
  blockinfile:
    path: /etc/apt/sources.list.d/docker.list
    marker: "# {mark} DOCKER SETTINGS - ANSIBLE MANAGED BLOCK"
    block: |
      deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ os_release }} stable
    create: true
  notify: apt_update

- meta: flush_handlers

- name: Install docker
  become: true
  apt:
    name: "{{ item  }}"
    state: present
  loop:
    - docker-ce
    - docker-ce-cli
    - containerd.io
